----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-update-handler
  labels:
    app: {{ .Release.Name }}-update-handler
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: flyway
          image: {{ .Values.rateLimiter.image }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-db-secrets
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DB_HOST):5432/$(DB_NAME)
            - name: FLYWAY_USER
              value: $(DB_USER)
            - name: FLYWAY_PASSWORD
              value: $(DB_PASSWORD)
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 10m
              memory: 128Mi
          env:
            - name: ENABLE_TELEMETRY
              value: "true"
            - name: HOROSCOPE_MODE
              value: openai_weekly
            - name: OPENAI_MODEL
              value: {{ .Values.openai.gptModel }}
            - name: OPENAI_IMAGE_MODEL
              value: {{ .Values.openai.imageModel }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://collector.opentelemetry-system:4317
            - name: RATE_LIMIT_ADMIN_PASS
              value: "false"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-telegram
            - secretRef:
                name: {{ .Release.Name }}-db-secrets
            - secretRef:
                name: {{ .Release.Name }}

