---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-update-handler
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-update-handler
  labels:
    app: {{ .Release.Name }}-update-handler
spec:
  replicas: 1
  revisionHistoryLimit: 0
  serviceName: {{ .Release.Name }}-update-handler
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      serviceAccountName: {{ .Release.Name }}
      volumes:
        - name: service-account
          secret:
            secretName: {{ .Release.Name }}
            items:
              - key: GSA_JSON
                path: ./gsa.json
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: flyway
          image: {{ .Values.rateLimiter.image }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-db-secrets
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DB_HOST):5432/$(DB_NAME)
            - name: FLYWAY_USER
              value: $(DB_USER)
            - name: FLYWAY_PASSWORD
              value: $(DB_PASSWORD)
      containers:
        - name: app
          image: {{ .Values.image.app }}:{{ .Values.appVersion }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ ALL ]
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - mountPath: /gcp
              name: service-account
              readOnly: true
          env:
            - name: ENABLE_TELEMETRY
              value: "true"
            - name: HOROSCOPE_MODE
              value: openai_weekly
            - name: OPENAI_MODEL
              value: {{ .Values.openai.gptModel }}
            - name: OPENAI_IMAGE_MODEL
              value: {{ .Values.openai.imageModel }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: https://api.honeycomb.io
            - name: RATE_LIMIT_ADMIN_PASS
              value: "false"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /gcp/gsa.json
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-telegram
            - configMapRef:
                name: {{ .Release.Name }}-gcp
            - secretRef:
                name: {{ .Release.Name }}-db-secrets
            - secretRef:
                name: {{ .Release.Name }}

